version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge_bravo_flp_app
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_test
    volumes:
      - ./:/app
    links:
      - db
      - db_test
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    container_name: challenge_bravo_flp_db
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - challenge_bravo_flp_db_volume:/var/lib/postgresql/data
  db_test:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "${DB_PORT_TEST}:5432"
    container_name: challenge_bravo_flp_db_test
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME_TEST}
volumes:
  challenge_bravo_flp_db_volume:
    driver: local
