version: "3.9"
services:
  postgres13:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_bravo
    ports:
      - 5434:5432
    volumes:
      - ./migration/initial-migration.sql:/docker-entrypoint-initdb.d/initial-migration.sql
  challenge_bravo:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 8000:8080
    volumes:
      - .:/opt/app/api
    depends_on:
      - postgres13
